Algoritmo "Dias da semana do Rafael Reis RA02610314"
// Lê um valor e mostra o dia da semana correspondente
Var

d : inteiro

Inicio

escreva ("Informe um valor de 1 a 7: ")
leia (d)

se (d > 7) ou (d < 1) entao
escreva ("Esse dia da semana não existe!")
fimalgoritmo

senao
     se d = 1 entao
     escreval ("Domingo")
     senao
     
        se d = 2 entao
        escreval ("Segunda-feira")
        senao

             se d = 3 entao
             escreval ("Terça-Feira")
             senao
             
                  se d = 4 entao
                  escreval ("Quarta-feira")
                  senao

             se d = 5 entao
             escreval ("Quinta-feira")
             senao
             
        se d = 6 entao
        escreval ("Sexta-feira")
        senao

     se d = 7 entao
     escreval ("Sábado")

fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

Fimalgoritmo