Algoritmo "Meses do ano do Rafael Reis RA02610314"
// Lê um valor e mostra o mês correspondente
Var

d : inteiro

Inicio

escreva ("Informe um valor de 1 a 12: ")
leia (d)

se (d > 12) ou (d < 1) entao
escreva ("Esse mês não existe!")
fimalgoritmo

senao
     se d = 1 entao
     escreval ("Janeiro")
     senao
     
        se d = 2 entao
        escreval ("Fevereiro")
        senao

             se d = 3 entao
             escreval ("Março")
             senao
             
                  se d = 4 entao
                  escreval ("Abril")
                  senao

             se d = 5 entao
             escreval ("Maio")
             senao
             
        se d = 6 entao
        escreval ("Junho")
        senao

     se d = 7 entao
     escreval ("Julho")
     senao
     
        se d = 8 entao
        escreval ("Agosto")
        senao

             se d = 9 entao
             escreval ("setembro")
             senao
             
             se d = 10 entao
             escreval ("outubro")
             senao

        se d = 11 entao
        escreval ("Novembro")
        senao

     se d = 12 entao
     escreval ("Dezembro")

fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

Fimalgoritmo