Algoritmo "Contas do Rafael Reis RA 02610314"
// Lê dois números e mostra a soma, a subtração e a multiplicação
Var

n1: inteiro
n2: inteiro

Inicio

escreva ("Informe um valor: ")
leia (n1)

escreva ("Informe mais um valor: ")
leia (n2)

escreval ("A soma de ", n1 , " e " , n2 , " é :" , n1 + n2)
escreval ("A subtração desses valores é: " , n1 - n2)
escreval ("Sua sua multiplicação é: " , n1 * n2)
escreval ("Por fim sua divisão é: ", n1 / n2)

Fimalgoritmo