Algoritmo "Média do Rafael Reis RA 02610314"
// Lê dois valores, mostra a média e se o aluno foi aprovado
Var

p1 : real
p2 : real

Inicio

escreva ("Informe sua primeira nota: ")
leia (p1)

escreva ("Agora informe sua segunda nota: ")
leia (p2)

escreval ("P1 = " , p1)
escreval ("P2 = " , p2)
escreval ("Sua média é: ", (p1 + p2) / 2)

se (p1 + p2) / 2 >= 7  entao
escreva ("Você foi aprovado!")

senao
escreva ("Você não passou!")

fimse

Fimalgoritmo