Algoritmo "Idades do Rafael Reis RA02610314"
// Lê a idade e mostra se é maior de idade,
// menor de idade ou maior de 60 anos

Var

i : inteiro

Inicio

escreva ("Informe a sua idade: ")
leia (i)

se i < 18 entao
escreval ("Se você tem " , i , " anos, você é menor de idade")
fimse

se (i >= 18) e (i < 60) entao
escreva ("Com" , i , " você é maior de idade")
fimse

se i >= 60 entao
escreval ("Ja pode tirar a carteirinha de gratuidade")
fimse

Fimalgoritmo